import { Suspense } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SlideLeft } from "./components/SlideLeft";
import { SlideRight } from "./components/SlideRight";
import Header from "./components/Header";
import { ThemeModeScript } from "flowbite-react";
import Loading from "./components/Loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
        <div className="flex flex-row min-h-screen bg-white dark:bg-gray-800 text-gray-800">
          <SlideLeft/>
          <div className="flex-1 min-h-full lg:w-2/3 md:w-full max-sm:w-[100%] max-sm:pl-[70px]">
            <Header/>
            <Suspense fallback={<Loading/>}>
              <main className="w-full max-h-[85vh] overflow-auto p-4">{children}</main>
            </Suspense>
          </div>
          <SlideRight/>
        </div>
      </body>
    </html>
  );
}
